language: python

matrix:
  include:
    - python: 3.6
      env: PENDULUM_EXTENSIONS=1
    - python: 3.6
      env: PENDULUM_EXTENSIONS=0
    - python: 3.7-dev
      env: PENDULUM_EXTENSIONS=1
    - python: 3.7-dev
      env: PENDULUM_EXTENSIONS=0

before_install:
  - pip install codecov

install:
  - virtualenv --python="$HOME/virtualenv/python3.6/bin/python" "$HOME/virtualenvs/venv-poetry"
  - $HOME/virtualenvs/venv-poetry/bin/pip install poetry --pre
  - $HOME/virtualenvs/venv-poetry/bin/poetry install -v
  - $HOME/virtualenvs/venv-poetry/bin/poetry build -v
  - |
      if [ "$PENDULUM_EXTENSIONS" == "1" ]; then
        find dist/ -iname pendulum*.whl -exec unzip -o {} 'pendulum/*' -d . \;
      fi

script: pytest --cov=pendulum --cov-config=.coveragerc tests/

after_success:
  - codecov
