build: false

environment:
  matrix:
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install poetry
  - "pip install poetry"

  # Install dependencies
  - "poetry install"
  # For some reason pytest-cov doesn't seem to be picked up
  # So reinstall with pip
  - "pip install pytest-cov"
  - "pip install codecov"

test_script:
  - "pytest --cov=pendulum --cov-config=.coveragerc tests/"

after_test:
  - "codecov"
