[package]
name = "pendulum"
version = "2.0.0-alpha0"
description = "Python datetimes made easy"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"

readme = 'README.rst'

homepage = "https://pendulum.eustace.io"
repository = "https://github.com/sdispater/pendulum"
documentation = "https://pendulum.eustace.io/docs"

keywords = ['datetime', 'date', 'time']

include = ['pendulum/**/*']

python-versions = "^3.6"


[dependencies]
tzlocal = "^1.3"
python-dateutil = "^2.6"
pytzdata = ">=2018.3"

[dev-dependencies]
pytest = "^3.4"
pytest-cov = "^2.5"
pytz = ">=2018.3"
babel = "^2.5"
cleo = "^0.6.1"
